version: '3.8'

services:
  app:
    build: .
    container_name: django_app
    volumes:
      - .:/app
    ports:
      - "8888:80"
    environment:
      - PYTHONUNBUFFERED=1
    command: ./start.sh